### ISSUE TITLE
Deploy 2024-04-18

### ISSUE THREAD

**Issue by gabmontes** [hemilabs/ethstats-server#1]
@dhidalgX please deploy this server to `testnet.ethstats.hemi.xyz`. Docker images already pushed to Docker Hub. Open port 3000 for incoming websocket traffic. Web server listening in port 3000 too.

Details in the [README](https://github.com/hemilabs/ethstats-server?tab=readme-ov-file#configuration). Pick any secret for `WS_SECRET`. It will be eventually shared with anyone else running Hemi nodes and willing to contribute to the stats.

**Comment by dhidalgX** [comment]
https://testnet.ethstats.hemi.xyz/ have been deployed.

```
k -nethstats get pods
NAME                               READY   STATUS    RESTARTS       AGE
ethstats-client-57b7b8f97c-fnvnx   1/1     Running   5 (106m ago)   3d
ethstats-server-689c848d9f-fbl24   1/1     Running   0              2d21h
```
